id: IB1193437
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T09:11:23+00:00'
last_modified: '2022-06-09T04:50:19.831893+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2MS2274
  title: གསུང་ཐོར་བུ། བློ་བཟང་མཆོག་གྲུབ་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    6CB6:
      image_group_id: I1KG906
      title: Volume 1 of gsung thor bu/_blo bzang mchog grub
      total_pages: 638
      order: 1
      base_file: 6CB6.txt
    BBC4:
      image_group_id: I1KG907
      title: Volume 2 of gsung thor bu/_blo bzang mchog grub
      total_pages: 654
      order: 2
      base_file: BBC4.txt
    AD73:
      image_group_id: I1KG908
      title: Volume 3 of gsung thor bu/_blo bzang mchog grub
      total_pages: 416
      order: 3
      base_file: AD73.txt
    DE44:
      image_group_id: I1KG909
      title: Volume 4 of gsung thor bu/_blo bzang mchog grub
      total_pages: 572
      order: 4
      base_file: DE44.txt
    A614:
      image_group_id: I1KG910
      title: Volume 5 of gsung thor bu/_blo bzang mchog grub
      total_pages: 582
      order: 5
      base_file: A614.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
