id: IB1193437
legacy_id: P008148
ocr_import_info:
  bdrc_scan_id: W2MS2274
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T09:07:04'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T09:13:45.635338+00:00'
last_modified: 2022-09-03 17:16:39.319728
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2MS2274
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW2MS2274
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་ཐོར་བུ། བློ་བཟང་མཆོག་གྲུབ།
  author: ཛ་འགོ་དགེ་བཤེས་བློ་བཟང་མཆོག་གྲུབ།
statistics:
  ocr_word_mean_confidence_index: 0.5086457644498426
  ocr_word_median_confidence_index: 0.44999998807907104
quality: null
bases:
  I1KG910:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG910
      total_pages: 582
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I1KG910.txt
    statistics:
      ocr_word_median_confidence_index: 0.5299999713897705
      ocr_word_mean_confidence_index: 0.5474963924975145
    legacy_id: v005
  I1KG909:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG909
      total_pages: 572
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1KG909.txt
    statistics:
      ocr_word_median_confidence_index: 0.38999998569488525
      ocr_word_mean_confidence_index: 0.46820376863244406
    legacy_id: v004
  I1KG908:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG908
      total_pages: 416
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG908.txt
    statistics:
      ocr_word_median_confidence_index: 0.44999998807907104
      ocr_word_mean_confidence_index: 0.5033188310508624
    legacy_id: v003
  I1KG907:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG907
      total_pages: 654
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG907.txt
    statistics:
      ocr_word_median_confidence_index: 0.5099999904632568
      ocr_word_mean_confidence_index: 0.5434202178950224
    legacy_id: v002
  I1KG906:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG906
      total_pages: 638
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG906.txt
    statistics:
      ocr_word_median_confidence_index: 0.38999998569488525
      ocr_word_mean_confidence_index: 0.47298600018349574
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
