id: P008148
initial_creation_type: ocr
source_metadata:
  id: bdr:W2MS2274
  title: གསུང་ཐོར་བུ། བློ་བཟང་མཆོག་གྲུབ་
  author: ''
  volumes:
    a35487c909c849dc8c2e187ffa458195:
      image_group_id: I1KG906
      title: ''
      volume_number: 1
      total_pages: 638
    f78181f76cc348419765fcd35b672997:
      image_group_id: I1KG907
      title: ''
      volume_number: 2
      total_pages: 654
    fe316349b13a41198aab343129201321:
      image_group_id: I1KG908
      title: ''
      volume_number: 3
      total_pages: 416
    1e64dcd93d5e461cb32b6b02d869eebf:
      image_group_id: I1KG909
      title: ''
      volume_number: 4
      total_pages: 572
    9d691266e1e44085809f9ec68860db44:
      image_group_id: I1KG910
      title: ''
      volume_number: 5
      total_pages: 582
ebook_metadata:
  title: གསུང་ཐོར་བུ། བློ་བཟང་མཆོག་གྲུབ་
  author: ''
  sku: P008148
  cover: cover.jpg
  layers:
  - pagination
