id: opecha:P008148
initial_creation_type: ocr
source_metadata:
  id: bdr:W2MS2274
  title: གསུང་ཐོར་བུ། བློ་བཟང་མཆོག་གྲུབ་
  volume:
    08fcd19fb0ff467183232d85c913b6ed:
      image_group_id: I1KG906
      title: Volume 1 of gsung thor bu/_blo bzang mchog grub
      volume_number: 1
      total_pages: 638
    f7bd983382d4451f8d9f1ccdbadab926:
      image_group_id: I1KG907
      title: Volume 2 of gsung thor bu/_blo bzang mchog grub
      volume_number: 2
      total_pages: 654
    c7a190570c6845bcbf92b968e68b18dc:
      image_group_id: I1KG908
      title: Volume 3 of gsung thor bu/_blo bzang mchog grub
      volume_number: 3
      total_pages: 416
    b2b4ca9c121c404ba305cbc1736bc6d5:
      image_group_id: I1KG909
      title: Volume 4 of gsung thor bu/_blo bzang mchog grub
      volume_number: 4
      total_pages: 572
    d9efd1ccdec54ccf8aa778951d790ac6:
      image_group_id: I1KG910
      title: Volume 5 of gsung thor bu/_blo bzang mchog grub
      volume_number: 5
      total_pages: 582
  author: ''
ebook_metadata:
  title: གསུང་ཐོར་བུ། བློ་བཟང་མཆོག་གྲུབ་
  author: ''
  sku: P008148
  cover: cover.jpg
  layers:
  - pagination
